CREATE DATABASE FotografandoDB;
USE FotografandoDB;
CREATE TABLE Utente(
	IDUser			INT NOT NULL AUTO_INCREMENT,
	username		VARCHAR(20) NULL,
	googleKey		VARCHAR(255) NULL UNIQUE,
	mail			VARCHAR(255) NOT NULL,
	score			SMALLINT,
	money			SMALLINT,
	CONSTRAINT PKUser PRIMARY KEY (IDUser)
);
CREATE TABLE Challenge(
	IDChallenge		SMALLINT NOT NULL AUTO_INCREMENT,
	description		VARCHAR(255) NOT NULL,
	title			VARCHAR(20)	NOT NULL,
	image			VARCHAR(255) NOT NULL,
	expire			DATETIME,
	stato			INT(1) NOT NULL,
	CONSTRAINT PKChallenge PRIMARY KEY(IDChallenge),
);
CREATE TABLE Photo(
	IDPhoto			INTEGER(10)	NOT NULL AUTO_INCREMENT,
	location		VARCHAR(255),
	owner			VARCHAR(20)	NOT NULL,
	
	CONSTRAINT PKPhoto PRIMARY KEY (IDPhoto),
	CONSTRAINT FKPhotoOwner FOREIGN KEY (owner) REFERENCES Utente(IDUser)
);
CREATE TABLE Rating(
	IDPhoto			INTEGER(10) NOT NULL,
	IDUser			VARCHAR(20)	NOT NULL,
	Rating			INT(1) DEFAULT NULL,
	
	CONSTRAINT FKRatingPhoto FOREIGN KEY (IDPhoto) REFERENCES Photo(IDPhoto),
	CONSTRAINT FKRatingUser FOREIGN KEY (IDUser) REFERENCES Utente(IDUser)
);
